### ISSUE TITLE
object.LambdaExpression.At(params object[] args) Error

### ISSUE THREAD

**Issue by OswaldNapier** [sgbj/MaximaSharp#5]
Hello, huge fan of your work.
However, I encounter this error mentioned in the title using At function.
It says"The type initializer for 'MaximaSharp.Maxima' threw an exception."
Here is the code:
            Expression<Func<double, double>> L1 = x => Math.Sqrt(x);
            double y = (double)L1.At(5.5);
I noticed the note you leave"Note: evaluating functions and basic operations are performed without the use of Maxima."
But the Plus, Minus functions work fine in my code.
I wonder why...

**Comment by sgbj** [comment]
Hi there! I agree it's strange that the Plus and Minus functions work, but you get that error with At. For you to be getting a type initializer error means that it's probably failing [around these lines](https://github.com/sgbj/MaximaSharp/blob/75067d7e045b9ed50883b5eb09803b4c8f391059/MaximaSharp/Maxima.cs#L14-L29). When I downloaded a fresh copy of this repository and added your two lines of code to the Test project, it worked for me. Maybe it's having trouble finding the Maxima exe file... Can you post the entire stack trace for the error you're receiving? It may look something like this:

```
System.TypeInitializationException: The type initializer for 'MaximaSharp.Maxima' threw an exception. ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at MaximaSharp.Maxima.NewMaxima() in D:\source\repos\MaximaSharp\MaximaSharp\Maxima.cs:line 28
   at MaximaSharp.Maxima..cctor() in D:\source\repos\MaximaSharp\MaximaSharp\Maxima.cs:line 14
   --- End of inner exception stack trace ---
   at MaximaSharp.Maxima.At(LambdaExpression f, Object[] args)
   at Test.Program.Main(String[] args) in D:\source\repos\MaximaSharp\Test\Program.cs:line 29
```

If the inner exception says `System.ComponentModel.Win32Exception: The system cannot find the file specified`, then that means it can't find the Maxima executable which should be located at `MaximaSharp\Test\bin\Debug\Maxima-5.30.0` You may need to copy the Maxima-5.30.0 folder into your project, or change the path it's looking for in the Maxima.cs file.

Hopefully that helps!

**Comment by OswaldNapier** [comment]
You are a true savior! I took your advice and it worked! 
Forgive me for being a new guy in this area. Have a nice day!
